### ISSUE TITLE
Resource requirements in CWL not respected when restarting

### ISSUE THREAD

**Issue by hisplan** [BD2KGenomics/toil#1655]
I'm using LSF as a batch system, and I have resource requirements defined in CWL as shown below:

```
requirements:
  InlineJavascriptRequirement: {}
  ResourceRequirement:
    ramMin: 20
    coresMin: 2
```

cwltoil correctly requested 20 GB of memory initially,

```
RESOURCE REQUIREMENT DETAILS:
 Combined: select[type == any] order[iounits] rusage[mem=20.00:iounits=1.00] sp
                     an[hosts=1] affinity[thread(1)*1]
 Effective: select[type == any] order[iounits] rusage[mem=20.00,iounits=1.00] s
                     pan[hosts=1] affinity[thread(1)*1]
```

but if I restart the job, cwltoil only requests 2 GB of memory.

```
 RESOURCE REQUIREMENT DETAILS:
 Combined: select[type == any] order[iounits] rusage[mem=2.00:iounits=1.00] spa
                     n[hosts=1] affinity[thread(1)*1]
 Effective: select[type == any] order[iounits] rusage[mem=2.00,iounits=1.00] sp
                     an[hosts=1] affinity[thread(1)*1]
```

**Comment by cket** [comment]
@hisplan that's bizarre.. Did this happen when you manually restarted an entire pipeline run or when a single job/step was retried automatically?

**Comment by hisplan** [comment]
We have a workflow that runs a couple of tools sequentially. One tool in the middle of the chain failed due to temp directory permission issue, so we fixed it and reran cwltoil with --restart, and the job failed again, but this time due to lack of memory (only 2 GB requested)

I also tried a very simple job that only has one tool associated with it - the same error received.

**Comment by mr-c** [comment]
@hisplan From the CWL v1.0 spec: http://www.commonwl.org/v1.0/CommandLineTool.html#ResourceRequirement
> `ramMin` Minimum reserved RAM in mebibytes (2**20)

`ramMin` is always in mebibytes (known as megabytes by some) -- `cwltoil` does correctly translate this, **but** different LSF clusters vary in their units and Toil has yet to adapt to that, see https://github.com/BD2KGenomics/toil/issues/1691

**Comment by izcram** [comment]
I think I'm running into similar issues using toil-cwl-runner on an LSF cluster. I've tried on a simple example, where I've tweaked the memory requirements in CWL after the command line tool failed. It seems, however, that toil doesn't pick up on that. Is this an expected behavior or a bug? 
It is important for us that we could restart a complex workflow with different resource requirements without having to restart from scratch.

I've tried the following using a recent commit on master (https://github.com/DataBiosphere/toil/commit/f5c737902ff7b93c2d806f981c316a85a80cfcb3).
I attempted to run a dummy `CommandLineTool` which uses roughly `$(inputs.bytes)` of RAM (see also https://stackoverflow.com/questions/20200982/how-to-generate-a-memory-shortage-using-bash-script):

```
cwlVersion: v1.0
class: CommandLineTool
requirements:
  - class: ShellCommandRequirement
  - class: ResourceRequirement
    ramMin: 1000
    ramMax: 1000

arguments:
  - shellQuote: false
    valueFrom: |
     yes | tr '\\n' 'x' | head -c $(inputs.bytes) | grep no > file.out
inputs:
  bytes:
    type: long
outputs:
 myfile:
   type: File
   outputBinding:
     glob: "file.out"
```

`bytes` parameter was set to  2147483648 so using overall a bit more than 2G.

Running it with `toil-cwl-runner --logDebug --logFile toil.log --retryCount=0 --batchSystem=lsf --disableCaching --jobStore myjobstore uses_memory.cwl arguments.yml` crashes as expected since LSF kills the job once it used up the 1000M it allocated:

```
Issued job 'PATH_DELETED/uses_memory.cwl' L/9/jobGtHAkU with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 1000.0 M
```

Changing `ramMin` and `ramMax` to `3000` in `uses_memory.cwl` and rerunning it with `toil-cwl-runner --logDebug --logFile toil.log --retryCount=0 --batchSystem=lsf --disableCaching --jobStore myjobstore --restart uses_memory.cwl arguments.yml` still leads to a crash and yields the following:

```
INFO:toil.leader:Issued job 'PATH_DELETED/uses_memory.cwl' L/9/jobGtHAkU with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G 
```                                                                                                                       

So interestingly toil seems to fall back to default settings after a restart.

I've tried a similar experiment where I ran toil locally (i.e. without `--batchSystem=lsf`) and manually killed the `grep` command and then restarted the job again with different memory requirements. Here, the new memory requirements were also ignored but the previous settings of 1000M were taken, not the default ones (the behavior might be different not because of local vs LSF but perhaps due to when/how the worker was killed).
