### ISSUE TITLE
secondaryFiles referenced inside tool not included when running a CWL workflow

### ISSUE THREAD

**Issue by johnbradley** [BD2KGenomics/toil#1730]
__cwltoil__ doesn't copy secondaryFiles to the staging area if they aren't specified in the top level workflow file. I have a workflow that runs fine in __cwltool__ but fails with 
```
[Errno 2] No such file or directory ...
```
when run via __cwltoil__.

# Simplified Example
Details for a workflow with a single input data file that runs `wc` on it's secondaryFile.

### Workflow file `wc-workflow.cwl` 
This file has input __somefile__ that doesn't reference any secondaryFiles. I expected this to be inferred from the tool file.
```
cwlVersion: v1.0
class: Workflow
inputs:
  somefile: 
    type: File
  
outputs:
  classout:
    type: File
    outputSource: wordcount/output

steps:
  wordcount:
    run: wordcount.cwl
    in:
      somefile: somefile
    out: 
      - output

```
### Tool file `wordcount.cwl`.
Specifies __somefile__ has a secondaryFile with the extension `.log`. This tool returns the output from `wc <somefile>.log`
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: wc
requirements:
  - class: InlineJavascriptRequirement
stdout: output.txt
label: wc pairs of files
doc: wc pairs
inputs:
  somefile:
    type: File
    secondaryFiles:
      - .log
arguments:
  - valueFrom: $(inputs.somefile.path + '.log')
outputs:
  output:
    type: stdout
```
###  Job order file `wordcount.json`
```
{
  "somefile": {
     "class": "File",
     "path": "data.txt"
  }
}
```

How to run:
```
cwltoil wc-workflow.cwl wordcount.json
```
Fails with:
```
ValidationException: :1:1: [Errno 2] No such file or directory: '/var/folders/fs/vv08ppmd1mj7g35hyq5m_7nr0000gp/T/toil-86b1c2c0-787e-4edf-a008-baaae56a25f9/tmp4gDukI/987fdd3e-0cda-415c-8c97-76824e1fdd72/tuuC8qN/inp/tmpExS9RP/data.txt.log'
```

It works fine with cwltool/cwl-runner:
```
cwltool wc-workflow.cwl wordcount.json 
```

# Work around
If I change my workflow file(`wc-workflow.cwl`) to include the secondaryFile information(duplicated from the tool file) __cwltoil__ works fine.
```
cwlVersion: v1.0
class: Workflow
inputs:
  somefile: 
    type: File
    secondaryFiles:
      - .log
...
```

Here is the repo from this example: https://github.com/johnbradley/toil-secondary-bug

Thanks.
