### ISSUE TITLE
per-step resource requirement support for CWL scripts

### ISSUE THREAD

**Issue by pimpim** [BD2KGenomics/toil#1775]
We bump into a similar limitation as mentioned in the IBM developer blog on toil/CWL: when writing a CWL script one gets only chance to define resource requirements, which is on the toil command line and this will apply to all steps in the CWL. Ideally, per step in CWL there would be room to give resource requests, or does that interfere with the CWL standard?

https://developer.ibm.com/storage/2017/05/04/cwl-workflow-lsf-toil/

"Resource requirement is specified on cwltoil command line thus applies to all jobs within the flow. One cannot specify resource requirement for individual jobs. To do that would require defining individual jobs in Python, not in CWL."

**Comment by mr-c** [comment]
Hello @pimpim 

This is already possible in CWL v1.0 using [step-level requirement overrides](http://www.commonwl.org/v1.0/Workflow.html#WorkflowStep):

```
class: Workflow
cwlVersion: v1.0

inputs: []

steps:
  first:
    run: first-step.cwl
    requirements:
      ResourceRequirement:    # overrides the ResourceRequirements in first-step.cwl
        minCores: 10
    in: {}
    out: []

outputs: []
```

FYI, these requirements can be calculated based upon the inputs themselves, but Toil's support for that is ongoing: https://github.com/BD2KGenomics/toil/issues/1647
