### ISSUE TITLE
nested directory getting lost between steps

### ISSUE THREAD

**Issue by gijzelaerr** [BD2KGenomics/toil#1969]
hi! I'm unsuccessfully trying to run our CWL pipeline with toil. It looks like somehow intermediate date products get lost. The pipeline runs fine with the CWL reference runner. My logfile is filled with errors like:

```
2017-11-26 11:19:34,177 - toil.leader - WARNING - W/2/jobLmwkno    WorkflowException: [Errno 2] No such file or directory: u'/vault-tina/gijs/prefactor-cwl/runs/run_2017-11-26-11-18-25/results/out_tmpdir2RF79v/calibrated.MS/OBSERVATION/table.lock'
```

The intermediate folder seems to be empty. My guess this is probably related to our data products being nested directory structures and maybe in combination with docker.

To reproduce this issue you could:
* clone our repository https://github.com/EOSC-LOFAR/prefactor-cwl/tree/b5c080d10c659232b46dd9dcb2d9e4c19cc9febc
* run `make toil` in the checkout

Requirements:
 * git-lfs
 * Docker
 * virtualenv

**Comment by gijzelaerr** [comment]
[output.txt](https://github.com/BD2KGenomics/toil/files/1503827/output.txt)

**Comment by DailyDreaming** [comment]
I posted an issue on your repo, but in attempting to use either `make run` or `make toil` I get the same error (running on Ubuntu 16.04):

`lifeisaboutfishtacos@TacoTruck:~/Desktop/LOFAR/prefactor-cwl$ make run`
`cd data && tar Jxvf L570745_uv_first10.MS.tar.xz`
`xz: (stdin): File format not recognized`
`tar: Child returned status 1`
`tar: Error is not recoverable: exiting now`
`Makefile:19: recipe for target 'data/L570745_SB000_uv_first10.MS/' failed`
`make: *** [data/L570745_SB000_uv_first10.MS/] Error 2`

**Comment by gijzelaerr** [comment]
this is problaby because you don't have git LFS installed

**Comment by DailyDreaming** [comment]
Sorry, I amended the error under your repo but forgot to reproduce it here.  I have git lfs, the issue is that your repo broke its data quota unfortunately.  Do you have a different source?

`Downloading data/L570745_uv_first10.MS.tar.xz (387 MB)`
`Error downloading object: data/L570745_uv_first10.MS.tar.xz (d6acef4): Smudge error: Error downloading data/L570745_uv_first10.MS.tar.xz`
`(d6acef40bcf795c5ae94232654414fece4a20eb75494577ea630fc663673b3c1): batch response: This repository is over its data quota.`
`Purchase more data packs to restore access.`

**Comment by mr-c** [comment]
Hey @DailyDreaming, here is a complete capture of the run with `--logDebug` 
https://drive.google.com/file/d/1Gv1TezB6YtpYJIwZVNqX3AMpjeSb3vEa/view?usp=sharing

**Comment by mr-c** [comment]
Just uncompress that and put it in `runs` and you should be able to restart Toil with the provided jobStore

**Comment by mr-c** [comment]
Here are the raw files from `data/`
[L570745_uv_first10.MS.tar.xz](https://drive.google.com/a/ucdavis.edu/file/d/1h-cDhNiEyjBz87vITZ2BolQbNyeboBGI/view?usp=sharing)
[L591513_SB000_uv_delta_t_4.MS.tar.xz](https://drive.google.com/a/ucdavis.edu/file/d/1xvXPpCUW8FqlP2tug82lWpKCP5iJRFrO/view?usp=sharing)

**Comment by gijzelaerr** [comment]
i've updated the Makefile and repo to pull the data from a FTP.

**Comment by gijzelaerr** [comment]
i'm running into the same issue with a different pipeline:

https://github.com/gijzelaerr/spiel

again, it is where we pass around a nested directory structure between steps.

**Comment by mr-c** [comment]
Here's a simplified minimal test case:

``` yaml
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: Workflow

inputs: []
outputs:
  deepest_dir:
    type: Directory
    outputSource: second/deeper_dir

steps:
  first:
    run:
      class: CommandLineTool
      baseCommand: [ mkdir, -p, deeply/nested/dir/structure ]
      inputs: []
      outputs:
        deep_dir:
          type: Directory
          outputBinding: { glob: deeply }
    in: {}
    out: [ deep_dir ]

  second:
    run:
      class: CommandLineTool
      baseCommand: [ touch, deeply/nested/dir/structure/ya ]
      requirements:
        InitialWorkDirRequirement:
          listing: [ $(inputs.dir) ]
      inputs:
        dir: Directory
      outputs:
        deeper_dir:
          type: Directory
          outputBinding: { glob: . }
 
    in: { dir: first/deep_dir }
    out: [ deeper_dir ]
```
