### ISSUE TITLE
error: argument --dirs_1 is required

### ISSUE THREAD

**Issue by ionox0** [BD2KGenomics/toil#2000]
I'm working on a tool to merge files from different directories into the same directory. I've upgraded to toil-3.12.0 which I believe now has support for Directory inputs, but I'm getting the following error which is confusing because I believe that I am indeed supplying the `dirs_1` input. Thanks very much, any advice would be appreciated. 

```
usage: /ifs/work/bergerm1/Innovation/sandbox/ian/roslin-pipelines/variant/1.3.1/bin/cwl/innovation-merge-directories/0.0.0/innovation-merge-directories.cwl
       [-h] --dirs_1 DIRS_1 --dirs_2 DIRS_2 [job_order]
/ifs/work/bergerm1/Innovation/sandbox/ian/roslin-pipelines/variant/1.3.1/bin/cwl/innovation-merge-directories/0.0.0/innovation-merge-directories.cwl: error: argument --dirs_1 is required
```

```
cwlVersion: v1.0

class: CommandLineTool

requirements:
  InlineJavascriptRequirement: {}
  ResourceRequirement:
    ramMin: 4
    coresMin: 1

baseCommand: [innovation_merge_directories]

inputs:
  dirs_1:
    type:
      type: array
      items: Directory
    inputBinding:
      position: 1

  dirs_2:
    type:
      type: array
      items: Directory
    inputBinding:
      position: 2

outputs:
  output_dir:
    type: Directory
    outputBinding:
      glob: .
```

```
dirs_1: [
  {class: Directory, path: '/home/johnsoni/roslin/setup/examples/innovation/dir_1'},
  {class: Directory, path: '/home/johnsoni/roslin/setup/examples/innovation/dir_2'}
  ]

dirs_2: [
  {class: Directory, path: '/home/johnsoni/roslin/setup/examples/innovation/dir_3'},
  {class: Directory, path: '/home/johnsoni/roslin/setup/examples/innovation/dir_4'}
  ]
```
