### ISSUE TITLE
Beginning of worker logs missing from logfile

### ISSUE THREAD

**Issue by ionox0** [BD2KGenomics/toil#2159]
Hello Toil team,

This is a follow up from https://github.com/common-workflow-language/cwltool/issues/703

I'm still seeing this issue after upgrading `cwltool` to `1.0.20180326152342`

The issue is that the logs from this [abra](https://github.com/mozack/abra/issues/29) tool do not always get logged into the cwltoil.log file. Specifically I'm missing the beginning of the logs. 

I linked to the above^ issue to point out the fact that the 0.92 version of the abra tool which we are currently using logs to standard error not stdout, which may be relevant.

This is the section of the logs that is missing (which I generated by using `echo` as the baseCommand instead of the abra jar):
https://gist.github.com/ionox0/d79acf464f7a2497ccfd270aecd8c5eb

### Versions:
cwltool version:
1.0.20180326152342
Toil version:
3.14.0

### Script used to run `toil-cwl-runner`
```
#!/bin/bash

toil-cwl-runner \
    --outdir ${output_directory} \
    --writeLogs	${output_directory}/log \
    --logFile ${output_directory}/log/cwltoil.log \
    --batchSystem ${batch_system} \
    --preserve-environment PATH PYTHONPATH \
    --defaultDisk 10G \
    --defaultMem 10G \
    --no-container \
    --linkImports \
    --disableCaching \
    --realTimeLogging \
    --workDir ${output_directory}/tmp \
    --jobStore file://${jobstore_path} \
    --cleanWorkDir onSuccess \
    --logDebug \
    --stats \
    ${workflow} \
    ${inputs_file}
```

### inputs.yaml
```
threads: 4
input_bams: 
- {class: File, path: '../test-data/standard_markDuplicates/Sample_ZS-msi-4506-pl-T01_IGO_05500_EF_41_standard_RG_MD.bam'}
- {class: File, path: '../test-data/standard_markDuplicates/Sample_ZS-msi-4506-pl-T01_IGO_05500_EF_42_standard_RG_MD.bam'}
input_bais: 
- {class: File, path: '../test-data/standard_markDuplicates/Sample_ZS-msi-4506-pl-T01_IGO_05500_EF_41_standard_RG_MD.bai'}
- {class: File, path: '../test-data/standard_markDuplicates/Sample_ZS-msi-4506-pl-T01_IGO_05500_EF_42_standard_RG_MD.bai'}

reference_fasta: './data/hg-fasta/VERSIONS/hg19/Homo_sapiens_assembly19.fasta'
targets: {class: File, path: '../test-data/start/pan-cancer-panel.sorted.bed'}

kmer: 43,53,63,83,93
mad: 1000
working_directory: ./data/abra_ian_temp_test_03-27

out: 
- Sample_ZS-msi-4506-pl-T01_IGO_05500_EF_41_standard_RG_MD.bam
- Sample_ZS-msi-4506-pl-T01_IGO_05500_EF_42_standard_RG_MD.bam
```

### abra.cwl
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: CommandLineTool

baseCommand:
- /bin/java

arguments:
- -Xmx20g
- -Djava.io.tmpdir=/scratch
- -jar
- ./data/abra-0.92-SNAPSHOT-jar-with-dependencies.jar

requirements:
  InlineJavascriptRequirement: {}
  ResourceRequirement:
    ramMin: 62000
    coresMin: 8

doc: |
  None

inputs:

  input_bams:
    type: File[]
    inputBinding:
      prefix: --in
      itemSeparator: ','
    secondaryFiles:
    - ^.bai

  working_directory:
    type: string
    inputBinding:
      prefix: --working

  reference_fasta:
    type: string
    inputBinding:
      prefix: --ref

  targets:
    type: File
    inputBinding:
      prefix: --targets

  threads:
    type: int
    inputBinding:
      prefix: --threads

  kmer:
    type: string
    inputBinding:
      prefix: --kmer

  mad:
    type: int
    inputBinding:
      prefix: --mad

  out:
    type: string[]
    inputBinding:
      itemSeparator: ','
      prefix: --out

outputs:

  bams:
    type: File[]
    outputBinding:
      glob: '*_IR.bam'
```

**Comment by mr-c** [comment]
@ionox0 If stderr output is important then I'd make that a separate output file

```
outputs:
  log: stderr
  bams:
    type: File[]
    outputBinding:
      glob: '*_IR.bam'
```
