### ISSUE TITLE
Issue with scatter step

### ISSUE THREAD

**Issue by ionox0** [BD2KGenomics/toil#2164]
I have a workflow with a scatter step and received this error at the end of the logs:

```
...
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/johnsoni/virtualenv/lib/python2.7/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=True).
DEBUG:toil.resource:Module dir is /home/johnsoni/virtualenv/lib/python2.7/site-packages
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/johnsoni/virtualenv/lib/python2.7/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=True).
DEBUG:toil.fileStore:LOG-TO-MASTER: Job a/g/jobJYZgex/g/tmpmuHQt5.tmp used 0.00% (4.5 KB [4608B] used, 10.0 GB [10737418240B] requested) at the end of its run.
Traceback (most recent call last):
  File "/home/johnsoni/virtualenv/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/home/johnsoni/virtualenv/lib/python2.7/site-packages/toil/job.py", line 1327, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/home/johnsoni/virtualenv/lib/python2.7/site-packages/toil/job.py", line 1272, in _run
    return self.run(fileStore)
  File "/home/johnsoni/virtualenv/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 583, in run
    copyjob[sc] = cwljob[sc][i]
IndexError: list index out of range
...
```

The workflow contains two scatter steps, and this error seems to happen after the first step is successful, but before starting the second step:
```

steps:

  umi_clipping:
    run: ../cwl_tools/marianas/ProcessLoopUMIFastq.cwl
    in:
      fastq1: fastq1
      fastq2: fastq2
      sample_sheet: sample_sheet
      umi_length: umi_length
      output_project_folder: output_project_folder
    out: [processed_fastq_1, processed_fastq_2, info, output_sample_sheet, umi_frequencies]
    scatter: [fastq1, fastq2, sample_sheet]
    scatterMethod: dotproduct

  module_1:
    run: ./module-1.cwl
    in:
      tmp_dir: tmp_dir
      fastq1: umi_clipping/processed_fastq_1
      fastq2: umi_clipping/processed_fastq_2
      adapter: adapter
      adapter2: adapter2
      reference_fasta: reference_fasta
      reference_fasta_fai: reference_fasta_fai
      add_rg_LB: add_rg_LB
      add_rg_ID: add_rg_ID
      add_rg_PU: add_rg_PU
      add_rg_SM: add_rg_SM
      add_rg_CN: add_rg_CN
      add_rg_PL: add_rg_PL
      md__create_index: md__create_index
      md__assume_sorted: md__assume_sorted
      md__compression_level: md__compression_level
      md__validation_stringency: md__validation_stringency
      md__duplicate_scoring_strategy: md__duplicate_scoring_strategy
    out: [bam, bai, md_metrics]
    scatter: [fastq1, fastq2, adapter, adapter2, add_rg_LB, add_rg_ID, add_rg_PU, add_rg_SM]
    scatterMethod: dotproduct
```

Any suggestions to help me debug would be appreciated!

### Versions
toil==3.15.0
cwltool==1.0.20180306140409

**Comment by mr-c** [comment]
Hello @ionox0  and thank you for your report. Is this reproducible with  just the latest version of `cwltool`?

**Comment by ionox0** [comment]
Of course, thank you for the response @mr-c . Sorry, I thought I was using the latest version. It looks like there is a `1.0.20180330141240` out now, can I upgrade to this version?

**Comment by mr-c** [comment]
@ionox0 `toil-cwl-runner` makes use of a specific version of `cwltool` (and modifies its behavior) so it would be helpful if you could make a new virtualenv with the latest `cwltool` in it and test there.

**Comment by ionox0** [comment]
Ok thank you. Is it not recommended to upgrade cwltool with `pip install cwltool --upgrade`? And instead should I always use the version of cwltool that is installed when installing toil-cwl-runner with `pip install toil'[cwl]'==3.15.0`? In that case I'm not sure how to use the latest `cwltool` if I'm using toil `3.15.0`. Maybe you could pass along the recommended version of both tools?

**Comment by mr-c** [comment]
For `toil-cwl-runner` from `pip install toil[cwl]` you should only use the version of `cwltool` that it has pinned its dependency on https://github.com/BD2KGenomics/toil/blob/master/setup.py#L38

To test with running `cwltool` instead of `toil-cwl-runner`, follow https://github.com/common-workflow-language/cwltool#install to make a new virtualenv seperate from your toil installation.

My apologies if this is confusing; it is our fault!

**Comment by ionox0** [comment]
Thank you again for the assistance, when testing the `cwltool ../workflows/standard_pipeline.cwl inputs.yaml` command in a new virtualenv with the latest cwltool (`1.0.20170413194156`) I receive several validation errors related to an expression tool that is part of the workflow. 

Are there any recent changes that were made around the `secondaryFiles`, `items`, or array `type` fields? And where can I find out more information about the `record` and `symbol` fields?
```
Tool definition file:///home/johnsoni/Innovation-Pipeline/cwl_tools/expression_tools/group_bams.cwl failed validation:
../cwl_tools/expression_tools/group_bams.cwl:3:1:   Object
                                                    `../cwl_tools/expression_tools/group_bams.cwl` is
                                                    not valid because
                                                      tried `ExpressionTool` but
../cwl_tools/expression_tools/group_bams.cwl:46:1:       the `outputs` field is not valid because
../cwl_tools/expression_tools/group_bams.cwl:48:3:         item is invalid because
../cwl_tools/expression_tools/group_bams.cwl:49:5:           the `type` field is not valid
                                                             because
                                                               - tried OutputRecordSchema but
../cwl_tools/expression_tools/group_bams.cwl:50:7:                 * the `type` field
                                                                   is not valid because
                                                                       the value 'array' is not a
                                                                       valid Record_symbol, expected 'record'
../cwl_tools/expression_tools/group_bams.cwl:51:7:                 * invalid field
                                                                   `items`, expected one of:
                                                                   'fields', 'type', 'label'
../cwl_tools/expression_tools/group_bams.cwl:49:5:             - tried OutputEnumSchema but
                                                                   * missing required field `symbols`
../cwl_tools/expression_tools/group_bams.cwl:50:7:                 * the `type` field
                                                                   is not valid because
                                                                       the value 'array' is not a
                                                                       valid Enum_symbol, expected 'enum'
../cwl_tools/expression_tools/group_bams.cwl:51:7:                 * invalid field
                                                                   `items`, expected one of:
                                                                   'symbols', 'type', 'label',
                                                                   'outputBinding'
../cwl_tools/expression_tools/group_bams.cwl:49:5:             - tried OutputArraySchema but
../cwl_tools/expression_tools/group_bams.cwl:51:7:                 the `items` field is
                                                                   not valid because
                                                                     - tried OutputRecordSchema but
../cwl_tools/expression_tools/group_bams.cwl:52:9:                       * the
                                                                         `type` field is not valid
                                                                         because
                                                                             the value 'array' is not
                                                                             a valid Record_symbol, expected 'record'
../cwl_tools/expression_tools/group_bams.cwl:53:9:                       *
                                                                         invalid field `items`,
                                                                         expected one of: 'fields',
                                                                         'type', 'label'
../cwl_tools/expression_tools/group_bams.cwl:54:9:                       *
                                                                         invalid field
                                                                         `secondaryFiles`, expected
                                                                         one of: 'fields', 'type',
                                                                         'label'
../cwl_tools/expression_tools/group_bams.cwl:51:7:                   - tried
                                                                     OutputEnumSchema but
                                                                         * missing required field
                                                                         `symbols`
../cwl_tools/expression_tools/group_bams.cwl:52:9:                       * the
                                                                         `type` field is not valid
                                                                         because
                                                                             the value 'array' is not
                                                                             a valid Enum_symbol, expected 'enum'
../cwl_tools/expression_tools/group_bams.cwl:53:9:                       *
                                                                         invalid field `items`,
                                                                         expected one of: 'symbols',
                                                                         'type', 'label',
                                                                         'outputBinding'
../cwl_tools/expression_tools/group_bams.cwl:54:9:                       *
                                                                         invalid field
                                                                         `secondaryFiles`, expected
                                                                         one of: 'symbols', 'type',
                                                                         'label', 'outputBinding'
../cwl_tools/expression_tools/group_bams.cwl:51:7:                   - tried
                                                                     OutputArraySchema but
../cwl_tools/expression_tools/group_bams.cwl:54:9:                       invalid
                                                                         field `secondaryFiles`,
                                                                         expected one of: 'items',
                                                                         'type', 'label',
                                                                         'outputBinding'
```

**Comment by mr-c** [comment]
Hello @ionox0 I just released a new version of `cwltool` that cleaned up some erroneous error messages; maybe `v1.0.20180403145700` will help you.

**Comment by ionox0** [comment]
I found that the cause of both of these errors^

The first is caused by the following situation:
```
# inputs.yaml
# param_1: [list, of, four, items]
# param_2: [list, of, not, four, items]

# workflow.cwl
# step_a:
#   in:
#       a: param_1
#       b: param_2
#   scatter: [param_1, param_2]
#   method: dotproduct
```
Can't scatter over params with different lengths with method = dotproduct

The second is casused by an incorrect placement of the `secondaryFiles` parameter:
```
outputs:
  grouped_bams:
    type:
      type: array
      items:
        type: array
        items: File
      secondaryFiles: ['^.bai']
```
